# Generated by Django 5.2.1 on 2025-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0002_alter_commentaire_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
