# Generated by Django 5.2.1 on 2025-05-26 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0003_alter_commentaire_date_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('genre', models.CharField(max_length=1)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être valide (ex: +33612345678 ou 0612345678)', regex='^\\+?[\\d\\s\\-]{7,15}$')])),
            ],
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
